version: "3.8"
services:
    
    mariadb:
      container_name: mariadb
      image: mariadb:10.4.13
      # ports:
      #     - '3306:3306'
      volumes:
          - ./mariadb/data:/var/lib/mysql
      environment:
          - MYSQL_ROOT_PASSWORD=aqwe123
      restart: always

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      ports:
        - "40001:80"
      environment:
        PMA_HOST: mariadb
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
      restart: always
      depends_on:
        - mariadb
    
    
    php:
      container_name: php
      build:
        context: ./php
      ports:
          - 9000:9000
      depends_on:
        - mariadb
      volumes:
            - ./app/public:/var/www/html
            - ./php/conf/dev.ini:/usr/local/etc/php/conf.d/php-dev.ini
            - ./logs/php/xdebug:/var/log/xdebug
      env_file:
          - ./php/.env
      restart: always
        
    nginx:
      container_name: nginx
      image: nginx:1.18.0
      ports:
        - '80:80'
      volumes:
          - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
          - ./logs/nginx:/var/log/nginx
          - ./app/public:/var/www/html
      env_file:
        - ./nginx/.env
      depends_on:
        - php
      links:
        - php
      restart: always
